<?php


namespace Iamamirsalehi\LaravelBalance\tests\Unit\Services\Balance;


use Iamamirsalehi\LaravelBalance\Models\Withdraw;
use Iamamirsalehi\LaravelBalance\Services\Balance\BalanceService;
use Iamamirsalehi\LaravelBalance\Tests\TestCase;

class WithdrawConfirmedTest extends TestCase
{
    public function test_we_can_confirm_a_withdraw()
    {
        list($user_id, $coin_id) = $this->getCoinAndUserId();

        BalanceService::deposit([
            'user_id' => 1,
            'coin_id' => 1,
            'price' => 300000
        ])->handle();

        BalanceService::withdrawUnconfirmedyet([
            'user_id' => 1,
            'coin_id' => 1,
            'price' => 200000
        ])->handle();

        $data = [
            'user_id' => $user_id,
            'coin_id' => $coin_id,
        ];

        $confirmed_withdraw = BalanceService::withdrawConfirmed($data)->handle();

        $this->assertIsArray($confirmed_withdraw);
        $this->assertEquals(Withdraw::CONFIRMED, $confirmed_withdraw['is_admin_confirmed']);
        $this->assertEquals(100000, $confirmed_withdraw['equity']);
        $this->assertEquals(-200000, $confirmed_withdraw['action_asset']);
        $this->assertEquals(100000, $confirmed_withdraw['asset']);
        $this->assertEquals(-200000, $confirmed_withdraw['action_liability']);
        $this->assertEquals(0, $confirmed_withdraw['liability']);
    }

    public function tearDown(): void
    {
        $this->truncate();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}